import functools

import werkzeug.security

from flask import redirect, request, session, url_for

#
# User accounts
#

#
# password hash generated by:
#
#   werkzeug.security.generate_password_hash('password')
#

class User(object):
  def __init__(self, username, pwhash, realname, email):
    self.username = username
    self.pwhash = pwhash
    self.realname = realname
    self.email = email

  def check_password(self, password):
    return werkzeug.security.check_password_hash(self.pwhash, password)


#
# User authentication
#

def login_required(f):
  @functools.wraps(f)
  def decorated_function(*args, **kwargs):
    if 'username' not in session:
      return redirect(url_for('login', next=request.url))
    return f(*args, **kwargs)

  return decorated_function

