import werkzeug.security

from flask import abort, session

#
# User accounts
#

import users

#
# password hash generated by:
#
#   werkzeug.security.generate_password_hash('password')
#

class User(object):
  def __init__(self, username, pwhash, realname, email):
    self.username = username
    self.pwhash = pwhash
    self.realname = realname
    self.email = email

  def check_password(self, password):
    return werkzeug.security.check_password_hash(self.pwhash, password)


accounts = { x[0]: User(*x) for x in users.accounts }


#
# User authentication
#

def auth_user(username, password):
  user = accounts.get(username, None)
  return user and user.check_password(password)


def auth_check():
  try:
    return session['username']
  except KeyError:
    abort(401)
